name: 'Appstage.io - Upload Files'
author: 'P4 Innovation Ltd'
description: 'Upload multiple files to your Appstage.io Live Builds release'
branding:
  icon: "upload-cloud"
  color: "red"
inputs:
  token:
    description: 'Project Access Token'
    required: true
  folder:
    description: 'Folder containing files to upload'
    required: true
  pattern:
    description: 'File upload pattern (regex), used in conjunction with "folder" input, defaults to ".*"'
    required: false
    default: '.*'
  host:
    description: 'API host, defaults to https://www.appstage.io'
    required: false
outputs:
  files:
    description: 'JSON list of files'
runs:
  using: 'node20'
  main: 'index.js'